apiVersion: v1
kind: Service
metadata:
  name: iris-classifier-service
spec:
  selector:
    app: iris-classifier # Selects the pods managed by your Deployment
  ports:
    - protocol: TCP
      port: 80 # The port you will access the service on
      targetPort: 80 # The port your container is listening on (from your Dockerfile)