# Name of your workflow
name: CI - Build and Push Docker Image

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds the image and pushes it to the GitHub Container Registry
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repo
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests
      #    NOTE: Change this command if your tests are in a different folder or use a different command
      - name: Run tests with pytest
        run: pytest

      # 5. Log in to the GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6. NEW STEP: Convert repository name to lowercase
      - name: Lowercase repository name
        id: string
        run: echo "repo_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # 7. MODIFIED STEP: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64  # <-- THIS IS THE KEY CHANGE did not work before
          tags: |
            ghcr.io/${{ steps.string.outputs.repo_name }}:latest
            ghcr.io/${{ steps.string.outputs.repo_name }}:${{ github.sha }}